<a href="https://colab.research.google.com/github/HWatanuki/Heroku_Tutorial/blob/main/Heroku_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1) Loading the Iris dataset as a pandas dataframe

In [1]:
import numpy as np
import pandas as pd
iris = pd.read_csv("./sample_data/Iris.csv")
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

2) Define x and y for training purposes

In [2]:
X = iris.drop('Species',axis=1)
y = iris['Species']
print(X)
print(y)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

[150 rows x 5 columns]
0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virgin

3) Encoding the species

In [3]:
from sklearn.preprocessing import LabelBinarizer
encoder = LabelBinarizer()
y = encoder.fit_transform(y)
print(y)

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 

4) Scaling the data

In [4]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaled_X = scaler.fit_transform(X)
print(scaled_X)

[[0.         0.22222222 0.625      0.06779661 0.04166667]
 [0.00671141 0.16666667 0.41666667 0.06779661 0.04166667]
 [0.01342282 0.11111111 0.5        0.05084746 0.04166667]
 [0.02013423 0.08333333 0.45833333 0.08474576 0.04166667]
 [0.02684564 0.19444444 0.66666667 0.06779661 0.04166667]
 [0.03355705 0.30555556 0.79166667 0.11864407 0.125     ]
 [0.04026846 0.08333333 0.58333333 0.06779661 0.08333333]
 [0.04697987 0.19444444 0.58333333 0.08474576 0.04166667]
 [0.05369128 0.02777778 0.375      0.06779661 0.04166667]
 [0.06040268 0.16666667 0.45833333 0.08474576 0.        ]
 [0.06711409 0.30555556 0.70833333 0.08474576 0.04166667]
 [0.0738255  0.13888889 0.58333333 0.10169492 0.04166667]
 [0.08053691 0.13888889 0.41666667 0.06779661 0.        ]
 [0.08724832 0.         0.41666667 0.01694915 0.        ]
 [0.09395973 0.41666667 0.83333333 0.03389831 0.04166667]
 [0.10067114 0.38888889 1.         0.08474576 0.125     ]
 [0.10738255 0.30555556 0.79166667 0.05084746 0.125     ]
 [0.11409396 0

5) Creating the Keras model

In [6]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model = Sequential()
model.add(Dense(units=4,activation='relu'))
model.add(Dense(units=32,activation='relu'))
model.add(Dense(units=16,activation='relu'))
# Last layer for multi-class classification of 3 species
model.add(Dense(units=3,activation='softmax'))
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

6) Training the model

In [7]:
model.fit(scaled_X,y,epochs=150)

Epoch 1/150
5/5 [==============================] - 3s 9ms/step - loss: 1.0980 - accuracy: 0.3133
Epoch 2/150
5/5 [==============================] - 0s 8ms/step - loss: 1.0929 - accuracy: 0.3333
Epoch 3/150
5/5 [==============================] - 0s 6ms/step - loss: 1.0898 - accuracy: 0.3333
Epoch 4/150
5/5 [==============================] - 0s 8ms/step - loss: 1.0871 - accuracy: 0.3333
Epoch 5/150
5/5 [==============================] - 0s 8ms/step - loss: 1.0838 - accuracy: 0.3333
Epoch 6/150
5/5 [==============================] - 0s 7ms/step - loss: 1.0803 - accuracy: 0.3333
Epoch 7/150
5/5 [==============================] - 0s 12ms/step - loss: 1.0762 - accuracy: 0.3333
Epoch 8/150
5/5 [==============================] - 0s 11ms/step - loss: 1.0715 - accuracy: 0.4600
Epoch 9/150
5/5 [==============================] - 0s 8ms/step - loss: 1.0661 - accuracy: 0.4733
Epoch 10/150
5/5 [==============================] - 0s 9ms/step - loss: 1.0598 - accuracy: 0.4867
Epoch 11/150
5/5 [=========

In [8]:
model.save("final_iris_model.h5")

7) Saving the scaler

In [9]:
import joblib
joblib.dump(scaler,'iris_scaler.pkl')

['iris_scaler.pkl']